project:
  type: website

website:
  title: "Angel Moreta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
      - href: blog/blog.qmd
        text: Blog

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css


